config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  root 'hello#index'
  get 'instas/my' => 'instas#my'
  resources :instas do
    resources :likes, only: [:create, :destroy]
  end
  post 'instas//:insta_id/comments' => 'comments#create', as: 'instum_comments'
  resources :relationships, only: [:create, :destroy]
  resources :posts do  
    resources :comments, only: [:create, :destroy] 
  end
end

app/models/insta.rb
class Insta < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
end

app/controllers/instas_controller.rb
class InstasController < ApplicationController
    before_action :authenticate_user!

    def index
        @instas = Insta.all
        @comment = Comment.new
        @rank_instas = Insta.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
        if params[:search] == nil
            @instas= Insta.all
        elsif params[:search] == ''
            @instas= Insta.all
        else
            @instas = Insta.where("body LIKE ? ",'%' + params[:search] + '%')
        end
    end

    def new
        @insta = Insta.new 
    end

    def create
        insta = Insta.new(insta_params)
        insta.user_id = current_user.id
        if insta.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @insta = Insta.find(params[:id])
        @comments = @insta.comments
        @comment = Comment.new
    end

    def edit
        @insta = Insta.find(params[:id])
    end

    def update
        insta = Insta.find(params[:id])
        if insta.update(insta_params)
            redirect_to :action => "show", :id => insta.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        insta = Insta.find(params[:id])
        insta.destroy
        redirect_to action: :index
    end
    
    private
    def insta_params
        params.permit(:body,:image)
    end
end

app/helpers/instas_helper.rb
module InstasHelper
end

app/views/instas/edit.html.erb
<%= form_with url: instas_path do |form| %>
    <%= form.label :body %>
    <%= form.text_field :body, :size => 140 %> 
    <%= form.submit "編集する" %>
    <%= link_to "一覧に戻る", insta_path %>
<% end %>

app/views/instas/index.html.erb
<div class="search">
    <%= form_tag({controller:"instas",action:"index"}, method: :get) do %>
        <%= text_field_tag :search , "検索" %>
        <%= submit_tag '検索する'  %>
    <% end %>
</div>
<div class="instas-container container">
    <div class="row">
            <% @rank_instas.each do |t| %>
                <div class="col-sm-6 col-12">
                    <div class="insta">
                        <div class="card" style="width: 18rem;">
                            <%= image_tag t.image_url, size: "250x200" if t.image? %>
                            <%= image_tag t.user.icon_url, class: 'icon', size: "100x100" if t.user.icon? %>
                            <div class="main-box">
                                <div class="left-container"><%= t.body %></div>
                                <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
                                <% if user_signed_in? %>
                                    <% if current_user.already_liked?(t) %>
                                        <%= link_to insta_like_path(id: t.id, insta_id: t.id), method: :delete do %>
                                            <i class="fas fa-heart"></i><%= t.likes.count %>                   
                                        <% end %>
                                    <% else %>
                                        <%= link_to insta_likes_path(id: t.id, insta_id: t.id), method: :post do %>
                                            <i class="far fa-heart"></i><%= t.likes.count %>                    
                                        <% end %>
                                    <% end %>
                                <% else %>
                                    <i class="far fa-heart"></i><%= t.likes.count %>           
                                <% end %>
                                    <%= link_to "詳細", insta_path(t.id) %>
                                <% if user_signed_in? && current_user.id == t.user_id %>
                                    <%= link_to "編集", edit_insta_path(t.id) %>
                                    <%= link_to "削除", insta_path(t.id), method: :delete %>
                                <% end %>  
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/instas/new.html.erb
<div class="post-container">
    <p class="title">新規投稿</p>
    <%= form_with url: instas_path do |form| %>
    <%= form.text_field :body,size: 140%>            <br>
            <%= form.label :image, "画像" %>
            <br>
            <%= form.file_field :image %>
            <br>
            <%= form.submit "送信" %>
    <% end %>
    <%= link_to "投稿一覧に戻る", instas_path %>
</div>

app/views/instas/show.html.erb
<h1>GeekInstagram</h1>
<h3>詳細</h3>
<div class="insta">
    <p><%= @insta.body %></p>
    <a href="/users/<%= @insta.user.id %>"><%= @insta.user.name %></a>
    <div class="comment-wrapper">
      <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
      <% if user_signed_in? && current_user.id == c.user_id %>
        <%=button_to "削除", post_comment_path(c.insta.id, c.id), method: :delete %>
      <% end %>
      <br>
      <% end %>
      <% if user_signed_in? %>
        <%= form_with(model: [@insta, @comment], local: true) do |f| %>
          <%= f.text_area :content %>
          <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        <% end %>
      <% end %>
    </div>
    <% if user_signed_in? %>
        <% if current_user.already_liked?(@insta) %>
            <%= link_to insta_like_path(@insta), method: :delete do %>
                <i class="fas fa-heart"></i><%= @insta.likes.count %>           
            <% end %>
        <% else %>
            <%= link_to insta_likes_path(@insta), method: :insta do %>
                <i class="far fa-heart"></i><%= @insta.likes.count %>            
            <% end %>
        <% end %>
    <% else %>
        <i class="far fa-heart"></i><%= @insta.likes.count %>    
    <% end %>
</div>
<%= link_to "編集する", edit_insta_path(@insta.id) %>
<%= link_to "一覧に戻る", instas_path %>