config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  root 'hello#index'
  get 'instas/my' => 'instas#my'
  resources :instas do
    resources :likes, only: [:create, :destroy]
  end
  post 'instas//:insta_id/comments' => 'comments#create', as: 'instum_comments'
  resources :relationships, only: [:create, :destroy]
  resources :posts do  
    resources :comments, only: [:create, :destroy] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :insta
end

app/models/insta.rb
class Insta < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :insta
  belongs_to :user
  validates_uniqueness_of :insta_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
    
    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }
  mount_uploader :icon, ImageUploader
  has_many :instas, dependent: :destroy 
  has_many :likes, dependent: :destroy
  has_many :liked_instas, through: :likes, source: :insta
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

    def already_liked?(insta)
      self.likes.exists?(insta_id: insta.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :icon])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :icon])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
    insta = Insta.find(params[:insta_id])
    comment = insta.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
    else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
    end
end

def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
        redirect_back(fallback_location: root_path)
    else
        flash.now[:alert] = 'コメント削除に失敗しました'
        render insta_path(@insta)
    end
end

private
    def comment_params
        params.require(:comment).permit(:content).merge(user_id: current_user.id, insta_id: params[:insta_id])
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
end

app/controllers/instas_controller.rb
class InstasController < ApplicationController
    before_action :authenticate_user!

    def index
        @instas = Insta.all
        @comment = Comment.new
        @rank_instas = Insta.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
        if params[:search] == nil
            @instas= Insta.all
        elsif params[:search] == ''
            @instas= Insta.all
        else
            @instas = Insta.where("body LIKE ? ",'%' + params[:search] + '%')
        end
    end

    def new
        @insta = Insta.new 
    end

    def create
        insta = Insta.new(insta_params)
        insta.user_id = current_user.id
        if insta.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @insta = Insta.find(params[:id])
        @comments = @insta.comments
        @comment = Comment.new
    end

    def edit
        @insta = Insta.find(params[:id])
    end

    def update
        insta = Insta.find(params[:id])
        if insta.update(insta_params)
            redirect_to :action => "show", :id => insta.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        insta = Insta.find(params[:id])
        insta.destroy
        redirect_to action: :index
    end
    
    private
    def insta_params
        params.permit(:body,:image)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(insta_id: params[:insta_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(insta_id: params[:insta_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :set_user
    
    def create
        following = current_user.follow(@user)
        if following.save
        flash[:success] = 'ユーザーをフォローしました'
        redirect_to @user
        else
        flash.now[:alert] = 'ユーザーのフォローに失敗しました'
        redirect_to @user
        end
    end
    
    def destroy
        following = current_user.unfollow(@user)
        if following.destroy
        flash[:success] = 'ユーザーのフォローを解除しました'
        redirect_to @user
        else
        flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
        redirect_to @user
        end
    end
    
    private
    def set_user
        @user = User.find(params[:follow_id])
    end
    
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/instas_helper.rb
module InstasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekInstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8a38c03ec3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <h1>GeekInstagram</h1>
      <div class="header-list">
        <ul>
        <li><%= link_to "ホーム", hello_index_path %></li>
        <li><%= link_to "新規投稿", new_insta_path %></li>
        <li><%= link_to "投稿一覧", instas_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "マイページへ", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "ログイン", user_session_path %></li>
          <li><%= link_to "サインアップ", new_user_registration_path %></li>
          <li><%= link_to "マイページへ", edit_user_registration_path %></li>

        <% end %>
        </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>